export enum Etat {
    NonLogue = "NON_LOGUE",
    DemandeLogon = "DEMANDE_LOGON",
    DemandeLogonAutorisee = "DEMANDE_LOGON_AUTORISEE",
    Logue = "LOGUE",
    DemandeConnexion = "DEMANDE_CONNEXION",
    Associe= "ASSOCIE",
    TransfertEnCours = "TRANSFERT_EN_COURS",
    NonTransferable = "NON_TRANSFERABLE",
    Transferable = "TRANSFERABLE",
    Transfere = "TRANSFERE",
    RetourALaVoix = "RETOUR_A_LA_VOIX",
    RetourALaVoixAcquitte = "RETOUR_A_LA_VOIX_ACQUITTE",
    DemandeDeconnexion = "DEMANDE_DECONNEXION",
    FinVol = "FIN_VOL",
    Unknown = "UNKNOWN",
}
